spring:
  profiles:
    active: dev
  datasource: #数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/searchblogengine
    username: root
    password: yuan
  redis:   #Redis 连接配置
    host: localhost
    port: 6379
    password: yuan
    database: 1
    max-active: 8
    max-wait: -1
    max-idle: 500
    min-idle: 0
    timeout: 0
  thymeleaf:  #thymeleaf 配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

#加载log4j2
#logging:
 # config: classpath:log4j2.xml
 # level: debug

mybatis:
  type-aliases-package: com.yuan.engine.entity
  #mapper加载路径
  mapper-locations: classpath:mapper/*.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml