spring:
  profiles:
    active: dev
  datasource: # 数据库连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/searchblogengine
    username: root
    password: yuan
  redis:   #Redis 配置信息
    host: localhost
    port: 6379
    password: yuan
    database: 1
    max-active: 8
    max-wait: -1
    max-idle: 500
    min-idle: 0
    timeout: 0
mybatis: #mybatsi 配置信息
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yuan.engine.entity
